% General(all are optional) structure of a class are:%
%======================1.Identification part==============================%
\ProvidesClass{tez_lisans_kaeu}[2022/10/27 v0.1 KAEU Lisans Tez sinifi]
\NeedsTeXFormat{LaTeX2e}

%======================2.Initial code=====================================%
%======================3.Declaration of options===========================%
%======================4.Execution of options=============================%
%======================5.Package loading==================================%
%======================6.Main code========================================%
%======================7.Special class file commands======================%
\LoadClass[a4paper,onecolumn,12pt]{report}





%-------------------------Dosya tipi ve gereken paket ayarları----------------%



%----------------------------- Kapak ayarları----------------------------------%


